### PR TITLE
Refactor to move service registration into a registry

### PR DESCRIPTION
**Pull request by bdraco**
This permits removing the broad exception catch that
was expanded to avoid a crash in when adding or
removing a service

### CODE REVIEW

**Comment by jstasiak** [comment]
Cheers, merged it manually in 2708fef6052f.

**Comment by bdraco** [comment]
Thank you 🙏🏻 

Can we get a release?

**Comment by jstasiak** [comment]
Thanks for the patch! Sure, 0.28.7 is out now. :)

**Comment by bdraco** [comment]
Thank you

**Pull request closed without merging**
