### PR TITLE
Fix flake8 E741 in setup.py

### PR DESCRIPTION
**Pull request by bdraco**
The CI was hitting on the `l` variable per
https://www.flake8rules.com/rules/E741.html

### CODE REVIEW

**Comment by bdraco** [comment]
Not sure why the coverage would change for a variable rename

**Comment by jstasiak** [comment]
Good question, I never wonder about those 0.04% changes, maybe there's something interesting behind those.

**Comment by bdraco** [comment]
Thanks @jstasiak   Would you be able to push a new release today so I can get these issues closed out on the Home Assistant side?

**Comment by jstasiak** [comment]
Sure, just released version 0.26.2 with your changes, enjoy!

**Comment by bdraco** [comment]
Thank you!

**Comment by jstasiak** [comment]
Thank you for the fixes. :)

**Pull request merged**
