### PR TITLE
A few minors issues are addressed and a new example is added

### PR DESCRIPTION
**Pull request by nameoftherose**

### CODE REVIEW

**Comment by stephenrauch** [comment]
I am not in charge of this repo, but you probably should squash all of those build commits. Also it is generally good form to add test coverage for any new lines of code.

To squash the changes for the last 11 commits, from a shell with the correct branch checked out you need to do:

```
git rebase -i HEAD~11
```

An editor should appear.  For all but the first line, at the beginning of the line change the word to squash.  Save the file.

Another editor should appear.  This will be the new comments for the squashed commit.  Probably want to delete all but the original comment.

Then you need to force push the changes by:

```
 git push origin {branch-name} --force
```

Change ``` {branch-name}``` to the appropriate branch name.  more details here:

https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

**Comment by nameoftherose** [comment]
Thank you, I will try to. All these commits were forced on me by travis for stylistic reasons.
It is quite obvious this is my first time, your help is welcome.
I would also appreciate any suggestions or references concerning test coverage.

**Comment by stephenrauch** [comment]
Test coverage:

My preferred way would be to revert the changes in my local work space. Then add test cases to show the error. Then add changes back in one at a time to see that the changes handle the error demonstrated by the test case.

For running the test cases, there are two ways I use:

1) pytest under pycharm. [pycharm](https://www.jetbrains.com/pycharm/) is great tool. It will not only run the test cases in an easy to follow manner, it will show you most of the stylistic problems right in the editor.

2) sign up for accounts on the various testing services and enable your forked repository in those services. Then, do any work on a personal branch. After that, when you push that branch to github, the testing service can pickup your changes and run the test suite on your repo. Easiest way to get to the testing service is to click on their badge, and then logon via your github account. Badges are generally on the main page below the files section. In the case of python-zeroconf, goto your repo[ main page](https://github.com/nameoftherose/python-zeroconf) and scroll down to the readme.rst section. Click on the ['build passing](https://travis-ci.org/jstasiak/python-zeroconf)' badge and also on the '[coverage xx%](https://coveralls.io/r/jstasiak/python-zeroconf)' badge to go to the various service provider pages.

I added a bunch of test coverage on pr #45 and some more on #49, so you can look at those if you like. In general, for your error handling, you need to figure out how to source a packet which has the error condition your new code will be handling.

Hopefully the owner of this repo will be back soon to pickup these various changes...

Cheers,

**Comment by nameoftherose** [comment]
@stephenrauch Thank you very much for your help

**Comment by stephenrauch** [comment]
@nameoftherose you are welcome. Those tests look great. I remember how out of sorts I was while trying to understand the workflow the first few times I committed changes on github.

Cheers,

PS. You are probably going to want to squash those changes down again.

**Comment by jstasiak** [comment]
Hey @nameoftherose, thanks for the patch. Would you mind cleaning the branch up? (Mainly I'm thinking about squashing related commits together and splitting some larger commits into logically-independent changes).

**Comment by bdraco** [comment]
This PR has gone stale, if you are still interested in merging this work, please open a new PR.  Thanks 👍

**Pull request closed without merging**
