### PR TITLE
Reduce the time window that the handlers lock is held

### PR DESCRIPTION
**Pull request by bdraco**
Unfortunately, I'm still seeing what I think are instances of #255 on very busy networks.

This builds on #258 to only hold the lock if we have an update.

@mattsaxon Does this violate any of your assumptions ?

### CODE REVIEW

**Comment by jstasiak** [comment]
@mattsaxon do you see any issues with this?

**Comment by mattsaxon** [comment]
@jstasiak looks very sensible to me!

**Comment by jstasiak** [comment]
Cheers, merging then!

**Comment by bdraco** [comment]
@jstasiak TYVM. Can we get a release? I'm hoping this solves the round of homekit cases 🤞

**Comment by jstasiak** [comment]
@bdraco No problem. Sure, 0.28.3 is out with your change!

**Comment by bdraco** [comment]
> @bdraco No problem. Sure, 0.28.3 is out with your change!

Thank you!

**Pull request merged**
