### PR TITLE
Fix i38 reaper iter exception

### PR DESCRIPTION
**Pull request by gbiddison**
Fix for #38 

#38 is an intermittent exception that crashes the Reaper thread.  
This fix seems correct & fairly harmless, but I haven't been able to verify whether this solves the problem since it is fairly rare.

### CODE REVIEW

**Comment by gbiddison** [comment]
This does not seem to fix the problem; I think this is because the inner loop where the list of entries is copied is where the iteration size change is happening.  I should be able to fix this.

**Comment by gbiddison** [comment]
I should know by next week whether this fixes the problem, I have a deploy coming up on Monday that should hit enough systems that the problem should be pretty frequent if it is still there.

**Comment by gbiddison** [comment]
Running for ~5 days on 25 machines and haven't seen the exception since making this change.

**Comment by gbiddison** [comment]
Running now for ~20 days on 25 machines, no exception and no apparent side-effects

**Comment by jstasiak** [comment]
Thank you @gbiddison, would you mind squashing the commits, leaving only the relevant changed and providing some comments in the code mentioning the fact that copying the values there is important?

**Comment by gbiddison** [comment]
will do

**Comment by jstasiak** [comment]
The fix (#44) has just been released in 0.17.5.

**Pull request closed without merging**
