### PR TITLE
Add support for multiple addresses when publishing a service

### PR DESCRIPTION
**Pull request by dtantsur**
This is a rebased and fixed version of PR #27, which also adds compatibility shim for ServiceInfo.address and does a proper deprecation for it.

### CODE REVIEW

**Comment by dtantsur** [comment]
Damn, I've been using `black` for half a day now, and I already hate it..

**Comment by jstasiak** [comment]
Nice!

**Comment by jstasiak** [comment]
I'm thinking – maybe it makes sense to keep `address` working as long as `len(addresses) == 1` and (in the future) make it throw an exception when there's more than a single address.

**Comment by dtantsur** [comment]
I'm on the fence about this. I don't think writing `info.addresses[0]` is so much harder than `info.address` and having two ways to do the same thing may be confusing. I'm worried about people just writing `info.address` without realizing that it won't always work.

**Comment by jstasiak** [comment]
Yeah, you're probably right.

**Comment by balloob** [comment]
Could you make a new release? This is actually fixing a bug where a `ServiceInfo` without an address would hit an assertion error.

**Comment by jstasiak** [comment]
@balloob Sure, version 0.23.0 has just been released.

**Pull request merged**
