### PR TITLE
Some code fixes to make sure IPv6 addresses are recorded and returned…

### PR DESCRIPTION
**Pull request by miphip**
… when browsing.

With these changes I could successfully find services with either ip_version=IpVersion.All, V4Only or V6Only. The returned service info would contain all the address records found in the service reponses.

(Great library, by the way!)

### CODE REVIEW

**Comment by jstasiak** [comment]
I'm wondering, is it possible/easy to write a test for this or add the relevant code to existing test(s)?

**Comment by dtantsur** [comment]
Will returning AAAA addresses break existing code? I'd expect a lot of people doing `inet_ntoa` on a `ServiceInfo.address`.

**Comment by dtantsur** [comment]
@jstasiak @miphip I've posted an updated PR since this has been inactive for a while: https://github.com/jstasiak/python-zeroconf/pull/191

**Comment by dtantsur** [comment]
I believe all changes from this PR have been included in #191.

**Pull request closed without merging**
