### PR TITLE
Ensure ServiceInfo populates all AAAA records

### PR DESCRIPTION
**Pull request by bdraco**
- Use get_all_by_details to ensure all records are loaded
  into addresses.

- Only load A/AAAA records from cache once in load_from_cache
  if there is a SRV record present

- Move duplicate code that checked if the ServiceInfo was complete
  into its own function

### CODE REVIEW

**Comment by bdraco** [comment]
Looks like GH still doesn't have routable IPv6 runners so this has to be tested locally instead

**Comment by bdraco** [comment]
zeroconf/test.py::Framework::test_launch_and_close_v4_v6 FAILED fails on macos, but it also fails on before this change and for a while.

**Comment by jstasiak** [comment]
Nice! Do you think you can add a test for this?

**Comment by bdraco** [comment]
I have a test for this but got side tracked fixing the CI flapping (https://github.com/jstasiak/python-zeroconf/pull/387 is a small change but took hours to track down) and I still need to figure out to get it to run without IPv6 support

I will try to get it merged today.

**Pull request merged**
