### PR TITLE
Use Adapter.index from ifaddr.

### PR DESCRIPTION
**Pull request by PhilippSelenium**
https://github.com/jstasiak/python-zeroconf/issues/279

### CODE REVIEW

**Comment by jstasiak** [comment]
Thank you. This needs to add an `ifaddr` version constraint so that we require version 0.1.7 or later (`Adpter.index` is added in 0.1.7).

**Comment by PhilippSelenium** [comment]
@jstasiak Done

**Comment by PhilippSelenium** [comment]
@jstasiak Should these comments be removed?
https://github.com/jstasiak/python-zeroconf/blob/master/zeroconf/__init__.py#L2053
https://github.com/jstasiak/python-zeroconf/blob/master/zeroconf/__init__.py#L2274

**Comment by jstasiak** [comment]
Yup

**Comment by jstasiak** [comment]
Cheers!

**Comment by jstasiak** [comment]
This has been released in 0.28.0.

**Pull request merged**
