### PR TITLE
Typing improvements

### PR DESCRIPTION
**Pull request by scop**

### CODE REVIEW

**Comment by scop** [comment]
disallow_untyped_calls just serves as a reminder to activate later. Kind of falls into the same category as adding the ones that don't require immediate action.

Moving stuff from mypy.ini to setup.cfg: less files, less clutter.

Running mypy on test code will uncover a bunch of problems with existing type hints (not only in the test code, but zerconf.py itself), subsequent commits which I'll submit separately a bit later will show these. Good to start testing already now in case something else crops up.

**Comment by jstasiak** [comment]
> disallow_untyped_calls just serves as a reminder to activate later. Kind of falls into the same category as adding the ones that don't require immediate action.

I think this should go into a separate commit with an appropriate explanation, it doesn't really belong in a commit named "Enable some more mypy warnings" since it doesn't do what the description says.

> Running mypy on test code will uncover a bunch of problems with existing type hints (not only in the test code, but zerconf.py itself), subsequent commits which I'll submit separately a bit later will show these. Good to start testing already now in case something else crops up.

Please include this information in the commit message.

The configuration should stay in mypy.ini, moving it to setup.cfg doesn't make it any better in my books and creates clutter in the repository history.

**Comment by jstasiak** [comment]
Actually I reconsidered - the mypy.ini/setup.cfg change can stay, have a few words of explanation in the commit message though.

**Comment by scop** [comment]
Tweaked as requested.

**Comment by jstasiak** [comment]
Cheers!

**Pull request merged**
