### PR TITLE
Fixes for OS X

### PR DESCRIPTION
**Pull request by estyrke**
* Listen on respond_sockets in addition to listen_socket
* Do not bind to respond_sockets in multicast mode

Without either of these changes, I get no replies at all when browsing for services using the browser example. I'm on a corporate network, and when connecting to a different network it works without these changes, so maybe it's something about the network configuration in this particular network that breaks the previous behavior.

Unfortunately, I have no idea how this affects other platforms, or what the changes really mean. However, it works for me and it seems reasonable to get replies back on the same socket where they are sent.

### CODE REVIEW

**Comment by jstasiak** [comment]
Thanks @estyrke. With this patch you can discover services in both corporate and other networks, right?

**Comment by estyrke** [comment]
@jstasiak, I'm afraid I have not tested for any regressions in other cases, or indeed very much at all. It's just something that seemed to work for me at the time.

**Comment by jstasiak** [comment]
@estyrke I rebased this PR in #270 to resolve conflicts.

**Comment by jstasiak** [comment]
Merged in fc92b1e2635868792aa7ebe937a9cfef2e2f0418.

**Comment by jstasiak** [comment]
This has been released in 0.28.0.

**Pull request closed without merging**
