### PR TITLE
Rebase PR #188 (Fixes for OS X) with resolved conflicts

### PR DESCRIPTION
**Pull request by jstasiak**

### CODE REVIEW

**Comment by jstasiak** [comment]
cc #188 

@estyrke while running examples with this seems fine both on Linux (tried it on Raspberry Pi) and on OS X this breaks the test suite on both of those systems for some reason, I'll try to figure out why.

**Comment by jstasiak** [comment]
I think the failures are due to the respond sockets not being assigned port 5353. Now their assigned a random port by the OS and, when a question gets sent through them it's received by the listening socket from a source port different than 5353 and this condition (from https://github.com/jstasiak/python-zeroconf/blob/beff99897f0a5ece17e224a7ea9b12ebd420044f/zeroconf/__init__.py#L1388)

```python
        elif msg.is_query():
            # Always multicast responses
            if port == _MDNS_PORT:
                self.zc.handle_query(msg, None, _MDNS_PORT)
```

doesn't trigger and a query gets ignored, which is followed by no answer being sent and the whole listener integration test crashes.

It's time for me to reread [RFC 6762](https://tools.ietf.org/html/rfc6762) in regards to sockets, interfaces and port numbers.

**Comment by jstasiak** [comment]
From RFC 6762:

```
   A compliant Multicast DNS querier, which implements the rules
   specified in this document, MUST send its Multicast DNS queries from
   UDP source port 5353 (the well-known port assigned to mDNS), and MUST
   listen for Multicast DNS replies sent to UDP destination port 5353 at
   the mDNS link-local multicast address (224.0.0.251 and/or its IPv6
   equivalent FF02::FB).
(...)
   The source UDP port in all Multicast DNS responses MUST be 5353 (the
   well-known port assigned to mDNS).  Multicast DNS implementations
   MUST silently ignore any Multicast DNS responses they receive where
   the source UDP port is not 5353.
```

**Comment by jstasiak** [comment]
@estyrke (or is it @estyrke-axis?) can you test this branch? I massaged it to the state that passes the test suite on Travis CI and my manual tests on both Mac and Linux were successful.

I'm actually thinking about removing the listening socket totally since we handle packets read from the respond sockets now, but I'll leave it for later.

**Comment by estyrke-axis** [comment]
Hi @jstasiak, sorry for the late reply! I made the commits using my work email, but created the PR using my personal github account, I guess that's the cause of the mixup.

Unfortunately, I haven't been able to test this branch in the original network where I had the problem, due to working from home at the moment. And to be honest, I don't even really remember what the specifics of the original problem were.

This branch does work in my home network, but then again, so does the master branch...

**Comment by jstasiak** [comment]
@estyrke-axis so I think I'll merge this as long as it doesn't break currently working usecases and, if in the future you discovered something's yet to be done, we can revisit this.

**Comment by jstasiak** [comment]
This has been released in 0.28.0.

**Pull request merged**
