### PR TITLE
Add py.typed marker (closes #199)

### LINKED ISSUE #199: Distribute the py.typed marker
We need the `py.typed` marker so that type checkers know to use type information provided by the package. In order to do that we need to switch from a single file (`zeroconf.py`) to a package which is unfortunate but seems necessary.

More information on this: https://www.python.org/dev/peps/pep-0561/

### PR DESCRIPTION
**Pull request by dtantsur**
This required changing to a proper package.

### CODE REVIEW

**Comment by dtantsur** [comment]
@jstasiak I'd like your review here since I'm not exactly familiar with typing in Python.

**Comment by jstasiak** [comment]
Yeah I think it looks all right. Maybe let's wait with merging this until the opendrop changes are merged to avoid merge conflicts.

**Comment by dtantsur** [comment]
Sure. Although git should be smart enough to figure out renames.

**Comment by jstasiak** [comment]
I think you're right – let's see how it goes.

**Pull request merged**
