### PR TITLE
Add support for AWDL interface on macOS

### PR DESCRIPTION
**Pull request by schmittner**
The API is inspired by Apple's NetService.includesPeerToPeer
(see https://developer.apple.com/documentation/foundation/netservice/1414086-includespeertopeer)

### CODE REVIEW

**Comment by schmittner** [comment]
@jstasiak not sure why build for pypy3.5 fails. My changes should not have any effects by default.

**Comment by jstasiak** [comment]
Hey, thanks for the patch, it's actually shorter than I expected after a quick look some time ago, nice!

> not sure why build for pypy3.5 fails. My changes should not have any effects by default.

One or two of the tests fail intermittently on PyPy for some reason, yet to be figured out.

Regarding the patch – I'm wondering about the API. Wouldn't it be better if we got rid of the `apple_p2p` public constructor parameter and instead detected internally if one of the `interfaces` addresses belongs to `awdl0`? It sounds like it should work, I can do it myself later. Here I'd at least change the `apple_p2p` behavior to crash on non-mac platforms and remove the `if platform.system() == 'Darwin'` check – the parameter says it's macOS-only already.

**Comment by schmittner** [comment]
Regarding the API: enabling AWDL automatically is a security risk. Services could get unintentionally advertised over AWDL which is an unauthenticated interface and anybody within range could overhear the announcements. I believe this is the reason why Apple implements its API like this.

That's why I would want to keep the flag. What we could do, however, is automatically set `apple_p2p` to `True` when the user selects `awdl0` as the only interface in which case we assume that the user knows what they're doing.

Regarding the platform check: isn't ignoring the setting on non-Apple platforms more graceful? Actually, I think it would make sense to check if the interface name is `awdl0` even on macOS before trying to set the option.
```python
if apple_p2p and platform.system() == 'Darwin' and is_awdl_interface():
    ...
```

**Comment by jstasiak** [comment]
> What we could do, however, is automatically set apple_p2p to True when the user selects awdl0 as the only interface in which case we assume that the user knows what they're doing.

This is what I had in mind, I should've been more explicit, sorry. I'd only enable it by default if the client code explicitly selects that one interface.

> Actually, I think it would make sense to check if the interface name is awdl0 even on macOS before trying to set the option.

Agreed. The way I'd expect it to work:

| `interfaces` | `apple_p2p` (`Optional[bool]`) | behavior |
| ------------| --------------| ---------|
| multiple interfaces | `None` or `False`  | no `SO_RECV_ANYIF` set on any socket |
| multiple interfaces | `True`  | `SO_RECV_ANYIF` set on a socket(s) corresponding to AWDL interface (if any)
| AWDL interface | `None` or `True`  | `SO_RECV_ANYIF` set |
| AWDL interface | `False`  | ? |

Is this tenable security-wise?

**Comment by jstasiak** [comment]
Alternatively maybe let's stick to the explicit way of enabling this (I'm kind of leaning this way, but I'll leave the decision to you):


| `interfaces` | `apple_p2p` (`bool`, default `False`) | behavior |
| ------------| --------------| ---------|
| multiple interfaces | `False`  | no `SO_RECV_ANYIF` set on any socket |
| multiple interfaces | `True`  | `SO_RECV_ANYIF` set on a socket(s) corresponding to AWDL interface (if any)
| AWDL interface | `True`  | `SO_RECV_ANYIF` set |
| AWDL interface | `False`  | no `SO_RECV_ANYIF` set |

**Comment by schmittner** [comment]
I also like the explicit way better. So, let's stick with that.

Unfortunately, it is currently not possible to set `SO_RECV_ANYIF` only on the AWDL interface since we are always binding to `('', port)` (see issue #193). If that is resolved (e.g., via #180), we can add such a check.

@jstasiak have you figured out the pypy3.5 problem?

**Comment by jstasiak** [comment]
It usually just goes away when another build is triggered, someone needs to investigate it further to get to the bottom of it – restarting CI is a workaround for now.

As to setting `SO_RECV_ANYIF` – fair enough, let's merge as is now once the linter is happy.

**Comment by jstasiak** [comment]
> @jstasiak not sure why build for pypy3.5 fails. My changes should not have any effects by default.

So the funny thing is the test that sometimes fails in Travis on PyPy should *never* pass and I'm trying to figure out why. This line won't work because `zeroconf` variable is not there https://github.com/jstasiak/python-zeroconf/blob/fcafdc1e285cc5c3c1f2c413ac9309d3426179f4/zeroconf/test.py#L883 and the whole test should collapse.

**Comment by jstasiak** [comment]
Ugh, sorry, I actually made myself believe the above – I renamed the variable locally while debugging and forgot about it. Ignore me.

**Pull request merged**
