### PR TITLE
Enable Mac OS CPython builds in CI

### PR DESCRIPTION
**Pull request by jstasiak**

### CODE REVIEW

**Comment by jstasiak** [comment]
@stephenrauch May I ask you for some help here? In 0924310415b79f0fa2523494d8a60803ec295e09 you added the following test code:

```python
# (...)
        # force a receive of an oversized packet
        packet = out.packet()
        s = zc._respond_sockets[0]

        # mock the zeroconf logger and check for the correct logging backoff
        call_counts = mocked_log_warn.call_count, mocked_log_debug.call_count
        # force receive on oversized packet
        s.sendto(packet, 0, (r._MDNS_ADDR, r._MDNS_PORT))
        s.sendto(packet, 0, (r._MDNS_ADDR, r._MDNS_PORT))
        time.sleep(2.0)
        zeroconf.log.debug(
            'warn %d debug %d was %s', mocked_log_warn.call_count, mocked_log_debug.call_count, call_counts
        )
        assert mocked_log_debug.call_count > call_counts[0]
# (...)
```

I'm trying to understand the meaning of those two `sendto` calls – they routinely fail on Mac OS due to:

```
ERROR: test_lots_of_names (test_zeroconf.Names)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/Users/travis/build/jstasiak/python-zeroconf/test_zeroconf.py", line 368, in test_lots_of_names

    s.sendto(packet, 0, (r._MDNS_ADDR, r._MDNS_PORT))

OSError: [Errno 40] Message too long
```

As a quick and dirty test I removed both of the `sendto` calls and all the tests passed on Linux and Mac OS.

**Comment by jstasiak** [comment]
FYI I'm considering removing those two `sendto()` calls if I don't learn anything about them being important.

**Comment by jstasiak** [comment]
#248 will resolve this I believe

**Comment by bdraco** [comment]
Looks like this is a solved issue as mac os CI builds are working 👍

**Comment by jstasiak** [comment]
That's a good spot – I've forgotten about this ticket. :)

**Pull request closed without merging**
