### PR TITLE
Rework exposing IPv6 addresses on ServiceInfo

### PR DESCRIPTION
**Pull request by dtantsur**
* Return backward compatibility for ServiceInfo.addresses by making
  it return V4 addresses only
* Add ServiceInfo.parsed_addresses for convenient access to addresses
* Raise TypeError if addresses are not provided as bytes (otherwise
  an ugly assertion error is raised when sending)
* Add more IPv6 unit tests

### CODE REVIEW

**Comment by dtantsur** [comment]
@jstasiak I don't know what I did to fix the PyPy problem, but here we go :) Actually, I suspect it may be sort of a race that got exposed by new tests. Dunno what to do about it. Opinions?

**Comment by jstasiak** [comment]
Yeah it may be a race condition. I can't really spend time on this right now so you decide what to do about it. :) I'm fine with just merging this.

**Comment by dtantsur** [comment]
I couldn't reproduce the failure locally after many attempts. I'd say we merge it and see if the issue ever repeats.

**Comment by dtantsur** [comment]
Thanks! Could you make a release whenever you're ready?

**Comment by jstasiak** [comment]
I added a milestone with few things I believe are needed for the new release: https://github.com/jstasiak/python-zeroconf/milestone/1 I can take care of all of them but it'll take a few days.

**Comment by jstasiak** [comment]
I went through the opendrop changes and narrowed down what's needed to be merged – it'll be possible to merge that code back without breaking backward compatibility so I decided to leave it for later and release what we have right now: version 0.24.0 with your patches has just been shipped.

**Comment by dtantsur** [comment]
w00t thanks! :)

**Pull request merged**
