### PR TITLE
added test for DNS-SD subtype discovery

### PR DESCRIPTION
**Pull request by strahlex**
Test for #37

### CODE REVIEW

**Comment by stephenrauch** [comment]
I am going to reopen the pull request.  I believe the code I added to better validate service names fixed  #37.  So i would like to merge this test only, not the fix which I believe to be obsolete at this point.

**Comment by strahlex** [comment]
If it is already in master then it did not fix the problem.

**Comment by strahlex** [comment]
Could also be that I am testing wrong because the `ServiceInfo` function now receives different parameters.

The problem was related to the subtype queries returning non-subtype results. Not sure if this was covered by the name checking code.

**Comment by strahlex** [comment]
@stephenrauch I think you where right just pulled your commits and test work out fine.

**Comment by strahlex** [comment]
@stephenrauch When will there be a new python-zeroconf release including the changes?

**Comment by stephenrauch** [comment]
@strahlex 

Release is ready, but only @jstasiak can push it to pypi.  Hopefully he will have some free time soon.

**Comment by jstasiak** [comment]
@strahlex @stephenrauch Just uploaded as 0.17.6 :)

**Pull request merged**
